spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://aa.c9diwssl1oou.ap-northeast-2.rds.amazonaws.com:3306/test?serverTimezone=Asia/Seoul
    username: admin
    password: foutune7
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 384d34ee8c8f1063c91501bd1abcd4d4
            client-name: Kakao
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            scope: profile_nickname, profile_image
            authorization-grant-type: authorization_code
            client-authentication-method: POST
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
  jwt:
    secretKey: 236979CB6F1AD6B6A6184A31E6BE37DB3818CC36871E26235DD67DCFE40
    blacklist:
      access-token: BlackList_AccessToken_
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    host: 127.0.0.1
    port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      generate-ddl: true
      format_sql: true
      use_sql_comments: true
  profiles:
    include: database

springdoc:
  version: 0.0.1
  default-consumes-media-type: application/json # media-type 디폴트값 설정
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    root: DEBUG